---
name: Code Style
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Head
        uses: actions/checkout@v2
        with:
          path: head
      - name: Install Tools
        run: |
          curl -sL https://apt.llvm.org/llvm-snapshot.gpg.key | \
            sudo apt-key add -
          sudo add-apt-repository \
            'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
          sudo apt update
          sudo apt install -y clang-format-11
      - name: Checkout Base
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: Check
        run: |
          cd "${GITHUB_WORKSPACE}"
          git diff --no-color --no-index -U0 --histogram --exit-code \
            --no-index -- base head > checkouts.diff || rc=$?
          if [[ $rc -eq 1 ]] ; then
            cd head
            data/check-style -d -o../code-style.diff < ../checkouts.diff
          else
            exit $rc
          fi
      - name: Archive Diff
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: diff
          path: code-style.diff
