---
name: Code Style
on:
  pull_request:
    branches:
    - master
    - 'cog-*'

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Head
        uses: actions/checkout@v4
      - name: Fetch Git History
        run: |
          git fetch --no-tags --prune --depth=1 \
            origin +refs/heads/master:refs/remotes/origin/master
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y clang-format-18 diffutils
      - name: Check
        run: |
          data/check-style -ocode-style.diff origin/master
      - name: Archive Diff
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: diff
          path: code-style.diff
